name: Test React App
on: push
jobs: 
  unit_test:
    runs-on: ubuntu-latest
    steps: 
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencides
        run: npm install
      - name: Test Application
        run: npm run test
